cmake_minimum_required(VERSION 3.24)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
foreach(required README.md BUILDING.md RELEASING.md DEPENDENCIES.md LICENSE)
  if(NOT EXISTS "${ROOT}/${required}")
    message(FATAL_ERROR "Missing canonical documentation: ${required}")
  endif()
endforeach()
foreach(license wxwidgets zlib pcre2 libpng tiff libjpeg-turbo liblzma nanosvg libwebp expat)
  if(NOT EXISTS "${ROOT}/third_party/licenses/${license}.txt")
    message(FATAL_ERROR "Missing third-party notice: ${license}")
  endif()
endforeach()
file(READ "${ROOT}/tools/release/make-release-tree.ps1" make_tree)
foreach(required LICENSE src include tests benchmarks assets tools packaging third_party)
  string(FIND "${make_tree}" "'${required}'" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "Release-tree allowlist is missing ${required}")
  endif()
endforeach()
file(READ "${ROOT}/tools/release/verify-release-tree.ps1" verify_tree)
string(FIND "${verify_tree}" "'LICENSE'" license_found)
if(license_found EQUAL -1)
  message(FATAL_ERROR "Release-tree verifier does not require LICENSE")
endif()
foreach(forbidden build .vs .git .worktrees artifacts vcpkg_installed)
  string(FIND "${verify_tree}" "'${forbidden}'" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "Release-tree verifier does not reject ${forbidden}")
  endif()
endforeach()
