cmake_minimum_required(VERSION 3.24)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)

if(NOT DEFINED SECURITY_CASE)
    message(FATAL_ERROR "SECURITY_CASE is required")
endif()

function(require_contains path needle)
    file(READ "${path}" content)
    string(FIND "${content}" "${needle}" pos)
    if(pos EQUAL -1)
        message(FATAL_ERROR "${SECURITY_CASE}: ${path} does not contain required text: ${needle}")
    endif()
endfunction()

function(require_not_contains path needle)
    file(READ "${path}" content)
    string(FIND "${content}" "${needle}" pos)
    if(NOT pos EQUAL -1)
        message(FATAL_ERROR "${SECURITY_CASE}: ${path} still contains forbidden text: ${needle}")
    endif()
endfunction()

function(require_exists path)
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "${SECURITY_CASE}: required path does not exist: ${path}")
    endif()
endfunction()

if(SECURITY_CASE STREQUAL "portable_automation")
    require_contains("${ROOT}/CMakeLists.txt" "NFF_PORTABLE_WINDOWS AND NFF_ENABLE_GUI_AUTOMATION")
elseif(SECURITY_CASE STREQUAL "windows_dll_load")
    require_contains("${ROOT}/CMakeLists.txt" "/DEPENDENTLOADFLAG:0x800")
    require_contains("${ROOT}/tools/release/verify-portable-windows.ps1" "/LOADCONFIG")
    require_contains("${ROOT}/tools/release/verify-portable-windows.ps1" "0x800")
elseif(SECURITY_CASE STREQUAL "portable_loadconfig_dumpbin_format")
    require_contains("${ROOT}/tools/release/verify-portable-windows.ps1" "0800\\s+Dependent\\s+Load\\s+Flag")
elseif(SECURITY_CASE STREQUAL "portable_reproducible_link")
    require_contains("${ROOT}/CMakeLists.txt" "\"/Brepro\"")
elseif(SECURITY_CASE STREQUAL "release_tree_hygiene")
    require_contains("${ROOT}/tools/release/make-release-tree.ps1" "'.gitattributes'")
elseif(SECURITY_CASE STREQUAL "release_tool_safety")
    require_contains("${ROOT}/tools/release/make-release-tree.ps1" ".nff-release-tree-managed")
    require_contains("${ROOT}/tools/release/package-portable-windows.ps1" ".nff-portable-output-managed")
elseif(SECURITY_CASE STREQUAL "crash_privacy")
    require_contains("${ROOT}/src/diagnostics/WindowsCrashReporter.cpp" "MiniDumpFilterMemory")
    require_contains("${ROOT}/src/diagnostics/WindowsCrashReporter.cpp" "MiniDumpWithoutOptionalData")
    require_not_contains("${ROOT}/src/diagnostics/WindowsCrashReporter.cpp" "Document contents are not included in diagnostics.")
elseif(SECURITY_CASE STREQUAL "sidebar_boundary")
    require_not_contains("${ROOT}/src/gui/wx/WxMainFrame.cpp" "options.followDirectorySymlinks = true;")
elseif(SECURITY_CASE STREQUAL "windows_acl_preserve")
    require_not_contains("${ROOT}/src/platform/windows/WindowsPlatform.cpp" "REPLACEFILE_IGNORE_MERGE_ERRORS")
elseif(SECURITY_CASE STREQUAL "portable_wx_config_compat")
    require_not_contains("${ROOT}/CMakeLists.txt" "find_package(wxWidgets 3.2 CONFIG REQUIRED COMPONENTS base core stc)")
    require_contains("${ROOT}/CMakeLists.txt" "find_package(wxWidgets CONFIG REQUIRED COMPONENTS base core stc)")
elseif(SECURITY_CASE STREQUAL "session_allocation_bounds")
    require_contains("${ROOT}/src/session/SessionStore.cpp" "countFitsRemaining")
    require_contains("${ROOT}/src/session/SessionStore.cpp" "minimumDocumentRecordBytes")
    require_contains("${ROOT}/src/session/SessionStore.cpp" "minimumPaneRecordBytes")
    require_contains("${ROOT}/src/session/SessionStore.cpp" "minimumViewRecordBytes")
elseif(SECURITY_CASE STREQUAL "settings_resource_caps")
    require_contains("${ROOT}/src/settings/AppSettings.cpp" "maximumInspectionSampleBytes")
    require_contains("${ROOT}/src/settings/AppSettings.cpp" "maximumLongLineThresholdBytes")
elseif(SECURITY_CASE STREQUAL "atomic_save_exclusive_temp")
    require_contains("${ROOT}/src/storage/AtomicSave.cpp" "CREATE_NEW")
    require_contains("${ROOT}/src/storage/AtomicSave.cpp" "O_EXCL")
elseif(SECURITY_CASE STREQUAL "posix_state_privacy")
    require_contains("${ROOT}/include/notepadFasaFiso/platform/Platform.hpp" "ensurePrivateDirectory")
    require_contains("${ROOT}/include/notepadFasaFiso/platform/Platform.hpp" "hardenPrivateFile")
    require_contains("${ROOT}/src/platform/Platform.cpp" "0700")
    require_contains("${ROOT}/src/platform/Platform.cpp" "0600")
    require_contains("${ROOT}/src/recovery/RecoveryManager.cpp" "ensurePrivateDirectory")
    require_contains("${ROOT}/src/app/ApplicationStateStore.cpp" "ensurePrivateDirectory")
elseif(SECURITY_CASE STREQUAL "posix_durable_atomic_save")
    require_contains("${ROOT}/src/storage/AtomicSave.cpp" "fsync")
    require_contains("${ROOT}/src/storage/AtomicSave.cpp" "syncParentDirectory")
elseif(SECURITY_CASE STREQUAL "footprint_cleanup")
    require_not_contains("${ROOT}/CMakeLists.txt" "src/app/StartupCoordinator.cpp")
    if(EXISTS "${ROOT}/src/app/StartupCoordinator.cpp" OR
       EXISTS "${ROOT}/include/notepadFasaFiso/app/StartupCoordinator.hpp")
        message(FATAL_ERROR "${SECURITY_CASE}: retired StartupCoordinator sources still exist")
    endif()
    require_not_contains("${ROOT}/src/gui/wx/WxMainFrame.cpp" "notepadFasaFiso/diagnostics/LocalDiagnostics.hpp")
    require_not_contains("${ROOT}/src/gui/wx/WxMainFrame.cpp" "diagnostics::write(")
    require_not_contains("${ROOT}/src/gui/wx/WxMainFrame.hpp" "lastFollowPollError_")
    require_not_contains("${ROOT}/src/gui/wx/WxApp.cpp" "wxInitAllImageHandlers()")
    require_contains("${ROOT}/src/gui/wx/WxApp.cpp" "#include <wx/imagpng.h>")
    require_contains("${ROOT}/src/gui/wx/WxApp.cpp" "wxImage::AddHandler(new wxPNGHandler);")
elseif(SECURITY_CASE STREQUAL "legal_distribution")
    require_exists("${ROOT}/THIRD_PARTY_NOTICES.txt")
    require_exists("${ROOT}/PRIVACY.md")
    require_exists("${ROOT}/third_party/licenses/appimage-runtime/LICENSE.txt")
    require_exists("${ROOT}/third_party/licenses/appimage-runtime/musl.txt")
    require_exists("${ROOT}/third_party/licenses/appimage-runtime/mimalloc.txt")
    require_exists("${ROOT}/third_party/licenses/appimage-runtime/squashfuse.txt")
    require_exists("${ROOT}/third_party/licenses/appimage-runtime/zstd.txt")
    require_exists("${ROOT}/tools/release/collect-appimage-licenses.sh")
    require_exists("${ROOT}/tools/release/collect-appimage-sources.sh")
    require_exists("${ROOT}/tools/release/collect-appimage-runtime-sources.sh")
    require_contains("${ROOT}/third_party/licenses/pcre2.txt" "Redistributions in binary form")
    require_contains("${ROOT}/third_party/licenses/appimage-runtime/LICENSE.txt" "AppImage runtime executable contains statically linked code")
    require_contains("${ROOT}/THIRD_PARTY_NOTICES.txt" "wxWidgets")
    require_contains("${ROOT}/THIRD_PARTY_NOTICES.txt" "PCRE2")
    require_contains("${ROOT}/THIRD_PARTY_NOTICES.txt" "AppImage type2 runtime")
    require_contains("${ROOT}/THIRD_PARTY_NOTICES.txt" "LGPL-2.1")
    require_contains("${ROOT}/THIRD_PARTY_NOTICES.txt" "This software is based in part on the work of the Independent JPEG Group.")
    require_contains("${ROOT}/THIRD_PARTY_NOTICES.txt" "University of California, Berkeley")
    require_contains("${ROOT}/tools/release/package-portable-windows.ps1" "THIRD_PARTY_NOTICES.txt")
    require_contains("${ROOT}/tools/release/package-portable-windows.ps1" "PRIVACY.md")
    require_contains("${ROOT}/tools/release/package-portable-windows.ps1" "'liblzma.txt'")
    require_contains("${ROOT}/tools/release/package-portable-windows.ps1" "LICENSE")
    require_not_contains("${ROOT}/tools/release/package-portable-windows.ps1" "exactly one EXE and no subdirectories")
    require_contains("${ROOT}/tools/release/package-appimage.sh" "collect-appimage-licenses.sh")
    require_contains("${ROOT}/tools/release/package-appimage.sh" "collect-appimage-sources.sh")
    require_contains("${ROOT}/tools/release/package-appimage.sh" "collect-appimage-runtime-sources.sh")
    require_contains("${ROOT}/tools/release/package-appimage.sh" "THIRD_PARTY_NOTICES.txt")
    require_contains("${ROOT}/tools/release/package-appimage.sh" "PRIVACY.md")
    require_contains("${ROOT}/tools/release/verify-appimage.sh" "THIRD_PARTY_NOTICES.txt")
    require_contains("${ROOT}/tools/release/verify-appimage.sh" "PRIVACY.md")
    require_contains("${ROOT}/tools/release/verify-appimage.sh" "common-licenses/LGPL-2.1")
    require_contains("${ROOT}/tools/release/verify-appimage.sh" "corresponding-source.tar.gz")
    require_contains("${ROOT}/tools/release/verify-appimage.sh" "runtime-source.tar.gz")
    require_contains("${ROOT}/tools/release/collect-appimage-licenses.sh" "$'\\t'")
    require_contains("${ROOT}/tools/release/collect-appimage-runtime-sources.sh" "1cc49bcf1e2ccd593c379adb17c9f85a36d619088296504de95b1d06215aebbf")
    require_contains("${ROOT}/tools/release/collect-appimage-runtime-sources.sh" "75849dce7cc37e4319b633df1f116ca895c71a12")
    require_contains("${ROOT}/tools/release/collect-appimage-runtime-sources.sh" "type2-runtime.list")
    require_contains("${ROOT}/tools/release/verify-appimage.sh" "runtime-source.list")
    require_contains("${ROOT}/tools/release/make-release-tree.ps1" "THIRD_PARTY_NOTICES.txt")
    require_contains("${ROOT}/tools/release/make-release-tree.ps1" "PRIVACY.md")
    require_contains("${ROOT}/tools/release/verify-release-tree.ps1" "collect-appimage-licenses.sh")
    require_contains("${ROOT}/tools/release/verify-release-tree.ps1" "collect-appimage-sources.sh")
    require_contains("${ROOT}/tools/release/verify-release-tree.ps1" "collect-appimage-runtime-sources.sh")
    require_contains("${ROOT}/RELEASING.md" "Legal/compliance")
    require_contains("${ROOT}/RELEASING.md" "corresponding source")
    require_contains("${ROOT}/PRIVACY.md" "No telemetry")
else()
    message(FATAL_ERROR "Unknown SECURITY_CASE: ${SECURITY_CASE}")
endif()
